name: Production Server Build Dry-Run

on: [pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Unlock git-crypt secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.0.2
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Source .env files
        needs: setup
        run: source .env && source ./src/mappening/utils/.env
      # can't really use caching here AFAIK as pip doesn't store installed packages in repo
      - name: Build Production Server
        run: make build-base && make build-dev
