name: Push Base Image
on:
    push:
        branches:
          # TODO: REMOVE THIS TEST LINE
            - will-zom-events-refactor
            - master
        paths:
            - 'src/Base-Dockerfile'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Unlock git-crypt secrets
          uses: sliteteam/github-action-git-crypt-unlock@1.0.2
          env:
            GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}  
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-1
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1
        - name: Build, tag, and push image to Amazon ECR
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: bmaps_backend_base
            IMAGE_TAG: ${{ github.sha }}
          run: |
            docker build -f ./src/Base-Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./src
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        - name: Logout of Amazon ECR
          if: always()
          run: docker logout ${{ steps.login-ecr.outputs.registry }}



            